# Generated by Django 5.0.6 on 2025-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_remove_profile_facebook_remove_profile_twitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_family_member',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_child_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_primary_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_spouse_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non-binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non-binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=100, null=True),
        ),
    ]
