# Generated by Django 5.0.6 on 2025-01-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_approvedemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('membership_choices', models.CharField(choices=[('primary', 'Primary Member'), ('spouse', 'Spouse'), ('child', 'Child'), ('guest', 'Guest')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='userauths.profile')),
            ],
        ),
    ]
