# Generated by Django 5.0.6 on 2025-01-17 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.CharField(blank=True, default='bunk', max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('max_occupants', models.IntegerField(blank=True, default=4, null=True)),
                ('booking_window', models.IntegerField(default=365, help_text='Days in advance allowed for booking')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='booking2.room2')),
            ],
        ),
        migrations.CreateModel(
            name='Booking2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('user', models.CharField(max_length=255)),
                ('occupants', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking2.room2')),
            ],
            options={
                'unique_together': {('room', 'check_in', 'check_out')},
            },
        ),
    ]
