# Generated by Django 5.0.6 on 2025-01-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_membernews_publicnews_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernews',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='publicnews',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
