# Generated by Django 5.0.6 on 2025-01-16 00:44

import hotel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_membernews_attachment_publicnews_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernews',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[hotel.validators.validate_attachment_file_size]),
        ),
        migrations.AlterField(
            model_name='publicnews',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[hotel.validators.validate_attachment_file_size]),
        ),
    ]
