# Generated by Django 5.0.6 on 2025-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_membernews_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='guest_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
    ]
