# Generated by Django 5.0.6 on 2025-01-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_roomtype_price_roomtype_child_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
