# Generated by Django 5.0.6 on 2025-01-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_blockeddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_adults',
            new_name='num_members',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'failed'), ('refunded', 'refunded')], default='initiated', max_length=100),
        ),
    ]
