# Generated by Django 5.0.6 on 2025-01-10 18:36

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_checked_in_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(blank=True, choices=[('Disabled', 'Disabled'), ('Live', 'Live')], default='published', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='hfid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='hfid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='hgid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='rtid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.CreateModel(
            name='FoodServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('service_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Special Event Meal', 'Special Event Meal')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomServices',
        ),
    ]
