# Generated by Django 5.0.6 on 2025-01-11 21:02

import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_alter_hotel_hid_alter_hotel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='bid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=25, prefix=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='nid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('internal_news_headline', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('internal_news_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('external_news_headline', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('external_news_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('is_news', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
