# Generated by Django 5.0.6 on 2025-01-12 20:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_alter_booking_booking_id_alter_bookmark_bid_and_more'),
        ('userauths', '0009_membershipchoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='member_choices',
            field=models.ForeignKey(default='primary', on_delete=django.db.models.deletion.CASCADE, to='userauths.membershipchoices'),
        ),
        migrations.CreateModel(
            name='MemberNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('is_news', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MemberNews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('is_news', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PublicNews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
