# Generated by Django 5.0.6 on 2025-01-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_booking_member_choices_membernews_publicnews_and_more'),
        ('userauths', '0009_membershipchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member_choices',
            field=models.ForeignKey(default='Primary Member', on_delete=django.db.models.deletion.CASCADE, to='userauths.membershipchoices'),
        ),
    ]
