# Generated by Django 5.0.6 on 2025-01-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_alter_booking_member_choices'),
        ('userauths', '0009_membershipchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.membershipchoices'),
        ),
    ]
