# Generated by Django 5.0.6 on 2025-01-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_alter_booking_member_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_children',
        ),
    ]
